Add ShiftAndCapsLock
dessalines/thumb-key pull request #1188
Opened 2024-12-11 05:08 UTC by K0baU

I added a new KeyAction called ShiftAndCapsLock. It does the same thing as ToggleShiftMode>ToggleCapsLock.

2024-12-11 21:57 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/JAKanaThumbKey.kt
> +                            action = ShiftAndCapsLock(true),
If enable is always true, you might as well remove it. Unless you plan on adding another one that disables shift mode.

2024-12-11 21:57 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt
> +            onToggleShiftMode(enable)
Can just make this true.

2024-12-14 13:59 UTC, dessalines requested changes
See comments above.

2024-12-15 05:33 UTC, K0baU commented
I added ShiftAndCapsLock(false) in line 233.

2024-12-15 13:18 UTC, dessalines approved these changes

2024-12-15 13:41 UTC, merged