Add TR split layout
dessalines/thumb-key pull request #1197
Opened 2024-12-16 21:18 UTC by ganyuss

Hello :wave: 

I added a new split layout for Turkish, based on [the letter frequency listed on Wikipedia](https://en.wikipedia.org/wiki/Letter_frequency#Relative_frequencies_of_letters_in_other_languages), as well as personal experience as a Turkish learner.

I tried to stick to the "popular vowels on the right, bottom to top, consonants on the left" guideline, even though I am not sure how well this applies to split layouts.

2024-12-16 23:34 UTC, dessalines requested changes

2024-12-16 23:34 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/utils/KeyboardLayout.kt
> +    TRTypeSplit(KB_TR_TYPESPLIT),
Read the line at the top of this file.

2024-12-17 13:26 UTC, dessalines commented
Need to run ./gradlew formatKotlin

2024-12-17 14:24 UTC, ganyuss commented
@dessalines I already did, and it does not change any line in the code. It looks like [the automation is broken](https://woodpecker.join-lemmy.org/repos/138/pipeline/2488/4).

2024-12-17 14:49 UTC, dessalines commented
Hrm.. I'll take a look.

2024-12-17 14:51 UTC, dessalines approved these changes

2024-12-17 14:53 UTC, merged