French layout improvement suggestion
dessalines/thumb-key pull request #126
Opened 2023-04-06 09:43 UTC by breversa

Following https://github.com/dessalines/thumb-key/issues/125

2023-04-07 13:22 UTC, dessalines commented
@CastelJeremy You already really did a review, but after @breversa updates the PR for your requested changes, hit approve and I'll know when this is ready to merge.

2023-04-10 10:15 UTC, breversa commented
@dessalines I've added a new commit with some needed changes.

What can I do now to have this layout implemented into Thumb-Key?

2023-04-15 12:14 UTC, breversa commented
@dessalines:
Since @CastelJeremy seems not to be around at the moment, can anyone else approve this?

2023-04-15 14:11 UTC, dessalines requested changes
You still have a lot of symbols on this keyboard, which should not be there, and added to the numeric keyboard, as part of a separate PR.

2023-04-15 14:18 UTC, breversa commented
I know ; I'd like to test that layout as it is before trimming it down.
If it helps, I'm fine with it being implemented as an "alternative" french layout rather that a "v2" french layout. :)

2023-04-15 14:59 UTC, dessalines commented
Please make the changes requested. Do not put symbols on anything but the numeric keyboard.

2023-04-15 18:41 UTC, CastelJeremy commented
Sorry for the late reply.

I agree with @dessalines, we should focus on the letter layout.

Also the pipeline is currently failing because of formatting errors, could you update your code to fix them ?
https://woodpecker.join-lemmy.org/dessalines/thumb-key/pipeline/90/3

Finally, we should stick to naming this update the V2 and as such you might need to update the following lines :

https://github.com/dessalines/thumb-key/blob/ecad1f328eb93a6a082cb0554bcd60034a84e8df/app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyFRv2.kt#L691
https://github.com/dessalines/thumb-key/blob/56a72984f03941f2e4b5666b1674d3c7f101c7c6/app/src/main/java/com/dessalines/thumbkey/utils/Types.kt#L95
https://github.com/dessalines/thumb-key/blob/56a72984f03941f2e4b5666b1674d3c7f101c7c6/app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt#L43
https://github.com/dessalines/thumb-key/blob/56a72984f03941f2e4b5666b1674d3c7f101c7c6/app/src/main/java/com/dessalines/thumbkey/utils/Utils.kt#L86

2023-05-01 14:35 UTC, CastelJeremy requested changes
Hey,
I reviewed your changes and added some comments where needed.

If you have some time, could you also look into my previous comment and update the `Utils.kt` and `Types.kt` files ? https://github.com/dessalines/thumb-key/pull/126#issuecomment-1509924679

Thank you for your work, now i really want to test this layout :D.

2023-05-01 14:35 UTC, CastelJeremy commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyFRv2.kt
> +                    ),
Missing a closing parenthesis right after this line.

2023-05-01 14:35 UTC, CastelJeremy commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyFRv2.kt
> +                        action = KeyAction.CommitText("c")
You can leave the `ç` on the TOP LEFT but you don't have to remove the default symbols which are standard on other layouts (`'`, `,`, `*`, `.`, `-`)

2023-05-01 14:35 UTC, CastelJeremy commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyFRv2.kt
>                      ),
Update this section with the changes done on the `MAIN` layout. (Restoring default symbols)

2023-05-16 13:05 UTC, dessalines commented
This has gone a while without updates, If someone wants to make a new PR, feel free.

2023-05-16 13:05 UTC, closed without merging

2023-05-16 13:09 UTC, breversa commented
Sorry, I've been very busy lately, and didn't expect that a quick improvement suggestion would turn into a "how does Git work again?" marathon.

2023-05-16 13:11 UTC, breversa commented
Sorry, I've been very busy lately, and didn't expect that a quick improvement suggestion would turn into a "how does Git work again?" marathon.

2023-05-22 17:45 UTC, dessalines commented
Sure, feel free to open a new PR.

2023-05-31 17:14 UTC, breversa commented
Is this correct now: app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyFRv2.kt ?

2023-06-01 11:28 UTC, dessalines commented
I'll get to your PR within a few days.