Added belarusian layout, as well as some other changes :)
dessalines/thumb-key pull request #211
Opened 2023-05-07 11:20 UTC by Chirikumbrah

Added **belarusian layout** and **belarusian layout with symbols**.
**Modified numeric layout** and added **russian layout with symbols**.
Muted symbols in **MessageEase EN layout with symbols**.

2023-05-08 20:41 UTC, dessalines reviewed
Also run `./gradlew formatKotlin` to pass lint.

2023-05-08 20:41 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyENv4Symbols.kt
Why is this file needed, if the programmer layout already exists?

2023-05-08 20:41 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyRUv2.kt
Add all these keyboards to the keyboard list in Types.kt

2023-05-10 15:16 UTC, Chirikumbrah commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyENv4Symbols.kt
@dessalines
I like standart symbols layout instead of programmer's symbols positions, so I desided to add standart symbols layout into the ENv4 :)

2023-05-10 16:07 UTC, dessalines requested changes

2023-05-10 16:07 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyENv4Programmer.kt
> +                        color = ColorVariant.MUTED
Thanks for muting these.

2023-05-10 16:07 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/utils/Types.kt
> +    MessageEaseEN("MessageEase English", 18),
The indexes should stay the same as they were before. IE UK should stay `14`

New keyboards should have a higher index, regardless of where they are in the list.

2023-05-11 15:27 UTC, dessalines commented
This failed compile, but I'm fixing it. We really need a good android image that can run on our CI.

2023-05-11 15:36 UTC, merged

2023-05-11 18:28 UTC, Chirikumbrah commented
@dessalines , I'll be happy to help you with that)

2023-05-11 18:45 UTC, Chirikumbrah commented
@dessalines , problem here)))
The layouts do not match the names XD
Tomorrow I'll fix it)

2023-05-11 19:00 UTC, dessalines commented
Cool