Update hungarian layout
dessalines/thumb-key pull request #334
Opened 2023-07-28 14:37 UTC by KnockoffFeline

Added Í letter that was forgotten from v1.

2023-07-28 20:03 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyHUv2.kt
> +val THUMBKEY_HU_V2_MAIN = KeyboardC(
You can keep this as its original name.

2023-07-28 20:03 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyHUv2.kt
> +val THUMBKEY_HU_V2_KEYBOARD_MODES: Map<KeyboardMode, KeyboardC> = mapOf(
You can leave these lines the same as before.

2023-08-09 10:25 UTC, dessalines requested changes

2023-08-09 10:25 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyHUv2.kt
> +val THUMBKEY_EN_V4_SHIFTED = KeyboardC(
Still incorrect here.

2023-08-09 10:25 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyHUv2.kt
> +val THUMBKEY_HU_V2_MAIN = KeyboardC(
You don't need to increase the version, leave the same as before.

2023-08-09 10:25 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeyHUv2.kt
> +val THUMBKEY_HU_V2_KEYBOARD_MODES: Map<KeyboardMode, KeyboardC> = mapOf(
This whole block you can leave as it was before.

2023-08-23 14:26 UTC, closed without merging

2023-09-17 05:55 UTC, KnockoffFeline commented
I am sorry, I am new to Github. I would like to approve these changes, but it would not let me. How do I get the changes through, then?

2023-09-17 11:44 UTC, dessalines commented
Make the changes that I requested above, then I'll see it. Watch a tutorial video on git.