Added greek layout
dessalines/thumb-key pull request #357
Opened 2023-08-21 20:02 UTC by iByteABit256

I used [this](https://www.researchgate.net/publication/220469197_Basic_Quantitative_Characteristics_of_the_Modern_Greek_Language_Using_the_Hellenic_National_Corpus) paper to determine the letter frequency for Greek which is based on the Hellenic National Corpus containing more than 48,000 written texts totaling 33 million words.

2023-08-21 20:45 UTC, iByteABit256 commented
### Without shift

![Screenshot_2023-08-21-23-43-32-733_org thoughtcrime securesms](https://github.com/dessalines/thumb-key/assets/57727226/3a2fad4b-b4fa-467e-80c2-9df23e693e62)

### With shift

![Screenshot_2023-08-21-23-41-33-124_org thoughtcrime securesms](https://github.com/dessalines/thumb-key/assets/57727226/5780f474-80a4-42d3-ab03-dc29a2fcb18e)

2023-08-21 20:47 UTC, iByteABit256 commented
## Without shift

![Screenshot_2023-08-21-23-45-53-513_org thoughtcrime securesms](https://github.com/dessalines/thumb-key/assets/57727226/a5aa6ab6-bb4b-4da1-8cd8-2ae023384c87)

---

## With shift
![Screenshot_2023-08-21-23-41-33-124_org thoughtcrime securesms](https://github.com/dessalines/thumb-key/assets/57727226/b98eeda1-3e9c-4ea8-9882-2576e2bf548f)

2023-08-23 04:53 UTC, dessalines requested changes

2023-08-23 04:53 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/utils/Types.kt
> +    ThumbKeyGRv1("Thumb-Key ελληνικά v1", 51),
Add this at the bottom of the list.

2023-08-23 14:05 UTC, dessalines approved these changes
Perfect, thanks!

2023-08-23 14:05 UTC, merged