Added Dracula Theme
dessalines/thumb-key pull request #376
Opened 2023-09-01 20:50 UTC by 0xFOSSMan

This is my first theme contribution and I don't have any Kotlin experience. Please excuse any errors.

2023-09-02 12:42 UTC, dessalines requested changes

2023-09-02 12:42 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/ui/theme/Color.kt
> +    }
The code didn't compile, probably because of additions like this. 

You also might need to run `./gradlew formatKotlin` to pass lint.

2023-09-02 16:30 UTC, 0xFOSSMan commented
./gradlew formatKotlin and ./gradlew lintKotlin worked on my machine. Pipeline borked

2023-09-02 18:03 UTC, dessalines approved these changes
No problem <3. Once I get the CI to pass, this will merge.

2023-09-05 13:55 UTC, 0xFOSSMan commented
> No problem <3. Once I get the CI to pass, this will merge.

managed it myself, I'm looking forward to seeing it in action :)

2023-09-05 15:51 UTC, merged