TypeSplit Japanese Hiragana/Katakana
dessalines/thumb-key pull request #541
Opened 2023-11-02 07:51 UTC by K0baU

2023-11-02 10:32 UTC, dessalines requested changes
Failed build, probably because of missing imports.

2023-11-03 02:10 UTC, K0baU commented
I used ENTypeSplit as a template. I didn't delete any import or use new variable. I have no idea what prevents build.

2023-11-03 13:34 UTC, dessalines commented
I'll clean this one up and try to get it working when I do the next release, no need to do anything for now.

2023-11-08 14:36 UTC, dessalines approved these changes

2023-11-08 14:45 UTC, merged