Added Italian translation
dessalines/thumb-key pull request #606
Opened 2024-01-05 17:00 UTC by flauta

2024-01-05 17:44 UTC, dessalines requested changes
Thx! Check the CI tho, lots of unicode escape errors.

2024-01-06 15:36 UTC, flauta reviewed
corrected non-escaped symbols

2024-01-06 16:03 UTC, flauta commented on app/src/main/res/values-it/strings.xml
> +    <string name="vibrate_warning">È necessario attivare 'Vibra al tocco' nelle impostazioni del telefono</string>
<string name="vibrate_warning">È necessario attivare \'Vibra al tocco\' nelle impostazioni del telefono</string>

2024-01-06 16:06 UTC, flauta reviewed
some non-escaped symbols

2024-01-06 16:06 UTC, flauta commented on app/src/main/res/values-it/strings.xml
> +    <string name="vibrate_warning">È necessario attivare 'Vibra al tocco' nelle impostazioni del telefono</string>
<string name="vibrate_warning">È necessario attivare \'Vibra al tocco\' nelle impostazioni del telefono</string>

2024-01-06 16:06 UTC, flauta commented on app/src/main/res/values-it/strings.xml
> +    <string name="finish_setup">Concludere l'impostazione</string>
<string name="finish_setup">Concludere l\'impostazione</string>

2024-01-06 16:10 UTC, flauta commented
I read the help on the reviews: can you merge the new strings from the comments as they say?

2024-01-06 16:45 UTC, dessalines commented
You need to escape things like single quotes.

2024-01-07 09:49 UTC, flauta commented
> You need to escape things like single quotes.

Yes I did it, but in the comments the escape gets striped away again. 
I'd better close this PR and open another one.

2024-01-07 09:49 UTC, closed without merging