Add long-press actions to keys
dessalines/thumb-key pull request #711
Opened 2024-02-10 18:00 UTC by ShortCircuit908

Add long-press actions to override default behaviors. Main use case is to insert a newline into a text field where it would otherwise perform a submit action.

2024-02-12 14:34 UTC, dessalines requested changes
Thx, this seems easy enough, but I still have to test it to make sure it doesn't slow down certain presses.

2024-02-12 14:34 UTC, dessalines commented on app/src/main/java/com/dessalines/thumbkey/keyboards/CommonKeys.kt
> +        longPress = KeyAction.CommitText("\n"),
These are hidden actions, so they need to be documented in some way. Add them both to the guide in the README.

2024-02-12 20:22 UTC, mpsijm commented
I have two questions:
1. https://developer.android.com/jetpack/compose/touch-input/pointer-input/tap-and-press#long-press-show suggests to include haptic feedback on long-press. Is that something we want?
2. It doesn't look like the duration of the long press is configurable. That doesn't have to be a problem, but MessagEase (and many other keyboards) allow configuring the long-press duration.

2024-02-12 23:10 UTC, dessalines commented
Good call, @ShortCircuit908 you should only need to add this:

`haptics.performHapticFeedback(HapticFeedbackType.LongPress)`

I'd say no on the configurable duration, we should just use the defaults on the combinedClickable.

2024-02-13 17:25 UTC, dessalines approved these changes
Tested and it seems to work well, thx!

2024-02-13 17:25 UTC, merged